import '@/global.scss'
import '@/globals.css'
import '@mantine/core/styles.css'
import 'mantine-datatable/styles.css'
import '@mantine/notifications/styles.css'
import '../layer.css'
import AppLayout from '@/features/layout'
import { ColorSchemeScript, MantineProvider } from '@mantine/core'
import { Notifications } from '@mantine/notifications'
import { SessionProvider } from 'next-auth/react'
import type { AppProps } from 'next/app'
import { Poppins } from 'next/font/google'
import Head from 'next/head'

const font = Poppins({ weight: '400', subsets: ['latin'] })

export default function App({ Component, pageProps }: AppProps) {
  return (
    <main className={font.className}>
      <Head>
        <title>Scale Doc</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <ColorSchemeScript defaultColorScheme="auto" />
      </Head>
      <MantineProvider
        defaultColorScheme="dark"
        theme={{ primaryColor: 'teal' }}
      >
        <SessionProvider>
          <AppLayout>
            <Notifications />
            <Component {...pageProps} />
          </AppLayout>
        </SessionProvider>
      </MantineProvider>
    </main>
  )
}
